/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.1 */
/* Tue Sep 29 19:45:53 2020 */

/* parameterized module instance */
gpif_fifo __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), .Q( ), 
    .Empty( ), .Full( ));
