/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.1 */
/* C:\lscc\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n gpif_fifo -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type ebfifo -sync_mode -depth 8192 -width 16 -regout -no_enable -pe -1 -pf -1 -sync_reset -fdc G:/cypress_prj/slfifo_prj/IP/fifo/gpif_fifo/gpif_fifo.fdc  */
/* Tue Sep 29 19:45:53 2020 */


`timescale 1 ns / 1 ps
module gpif_fifo (Data, Clock, WrEn, RdEn, Reset, Q, Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] Data;
    input wire Clock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    output wire [15:0] Q;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire rden_i_inv;
    wire fcnt_en;
    wire empty_i;
    wire empty_d;
    wire full_i;
    wire full_d;
    wire ifcount_0;
    wire ifcount_1;
    wire bdcnt_bctr_ci;
    wire ifcount_2;
    wire ifcount_3;
    wire co0;
    wire ifcount_4;
    wire ifcount_5;
    wire co1;
    wire ifcount_6;
    wire ifcount_7;
    wire co2;
    wire ifcount_8;
    wire ifcount_9;
    wire co3;
    wire ifcount_10;
    wire ifcount_11;
    wire co4;
    wire ifcount_12;
    wire ifcount_13;
    wire co6;
    wire cnt_con;
    wire co5;
    wire cmp_ci;
    wire rden_i;
    wire co0_1;
    wire co1_1;
    wire co2_1;
    wire co3_1;
    wire co4_1;
    wire co5_1;
    wire cmp_le_1;
    wire cmp_le_1_c;
    wire cmp_ci_1;
    wire fcount_0;
    wire fcount_1;
    wire co0_2;
    wire fcount_2;
    wire fcount_3;
    wire co1_2;
    wire fcount_4;
    wire fcount_5;
    wire co2_2;
    wire fcount_6;
    wire fcount_7;
    wire co3_2;
    wire fcount_8;
    wire fcount_9;
    wire co4_2;
    wire fcount_10;
    wire fcount_11;
    wire co5_2;
    wire wren_i;
    wire wren_i_inv;
    wire fcount_12;
    wire fcount_13;
    wire cmp_ge_d1;
    wire cmp_ge_d1_c;
    wire iwcount_0;
    wire iwcount_1;
    wire w_ctr_ci;
    wire wcount_0;
    wire wcount_1;
    wire iwcount_2;
    wire iwcount_3;
    wire co0_3;
    wire wcount_2;
    wire wcount_3;
    wire iwcount_4;
    wire iwcount_5;
    wire co1_3;
    wire wcount_4;
    wire wcount_5;
    wire iwcount_6;
    wire iwcount_7;
    wire co2_3;
    wire wcount_6;
    wire wcount_7;
    wire iwcount_8;
    wire iwcount_9;
    wire co3_3;
    wire wcount_8;
    wire wcount_9;
    wire iwcount_10;
    wire iwcount_11;
    wire co4_3;
    wire wcount_10;
    wire wcount_11;
    wire iwcount_12;
    wire iwcount_13;
    wire co6_1;
    wire co5_3;
    wire wcount_12;
    wire wcount_13;
    wire ircount_0;
    wire ircount_1;
    wire r_ctr_ci;
    wire rcount_0;
    wire rcount_1;
    wire ircount_2;
    wire ircount_3;
    wire co0_4;
    wire rcount_2;
    wire rcount_3;
    wire ircount_4;
    wire ircount_5;
    wire co1_4;
    wire rcount_4;
    wire rcount_5;
    wire ircount_6;
    wire ircount_7;
    wire co2_4;
    wire rcount_6;
    wire rcount_7;
    wire ircount_8;
    wire ircount_9;
    wire co3_4;
    wire rcount_8;
    wire rcount_9;
    wire ircount_10;
    wire ircount_11;
    wire co4_4;
    wire rcount_10;
    wire rcount_11;
    wire ircount_12;
    wire ircount_13;
    wire co6_2;
    wire scuba_vhi;
    wire scuba_vlo;
    wire co5_4;
    wire rcount_12;
    wire rcount_13;

    AND2 AND2_t3 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_3 (.A(full_i), .Z(invout_1));

    AND2 AND2_t2 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_2 (.A(empty_i), .Z(invout_0));

    AND2 AND2_t1 (.A(wren_i), .B(rden_i_inv), .Z(cnt_con));

    XOR2 XOR2_t0 (.A(wren_i), .B(rden_i), .Z(fcnt_en));

    INV INV_1 (.A(rden_i), .Z(rden_i_inv));

    INV INV_0 (.A(wren_i), .Z(wren_i_inv));

    defparam LUT4_1.initval =  16'h3232 ;
    ROM16X1A LUT4_1 (.AD3(scuba_vlo), .AD2(cmp_le_1), .AD1(wren_i), .AD0(empty_i), 
        .DO0(empty_d));

    defparam LUT4_0.initval =  16'h3232 ;
    ROM16X1A LUT4_0 (.AD3(scuba_vlo), .AD2(cmp_ge_d1), .AD1(rden_i), .AD0(full_i), 
        .DO0(full_d));

    defparam pdp_ram_0_0_7.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_0_7.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_0_7.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_0_7.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_0_7.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_0_7.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_0_7.GSR = "ENABLED" ;
    defparam pdp_ram_0_0_7.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_0_7.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_0_7.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_0_7.DATA_WIDTH_B = 2 ;
    defparam pdp_ram_0_0_7.DATA_WIDTH_A = 2 ;
    DP16KD pdp_ram_0_0_7 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(scuba_vlo), .DIA1(Data[1]), .DIA0(Data[0]), .ADA13(wcount_12), 
        .ADA12(wcount_11), .ADA11(wcount_10), .ADA10(wcount_9), .ADA9(wcount_8), 
        .ADA8(wcount_7), .ADA7(wcount_6), .ADA6(wcount_5), .ADA5(wcount_4), 
        .ADA4(wcount_3), .ADA3(wcount_2), .ADA2(wcount_1), .ADA1(wcount_0), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(rcount_12), .ADB12(rcount_11), 
        .ADB11(rcount_10), .ADB10(rcount_9), .ADB9(rcount_8), .ADB8(rcount_7), 
        .ADB7(rcount_6), .ADB6(rcount_5), .ADB5(rcount_4), .ADB4(rcount_3), 
        .ADB3(rcount_2), .ADB2(rcount_1), .ADB1(rcount_0), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(Q[1]), .DOB0(Q[0]))
             /* synthesis MEM_LPC_FILE="gpif_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_1_6.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_1_6.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_1_6.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_1_6.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_1_6.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_1_6.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_1_6.GSR = "ENABLED" ;
    defparam pdp_ram_0_1_6.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_1_6.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_1_6.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_1_6.DATA_WIDTH_B = 2 ;
    defparam pdp_ram_0_1_6.DATA_WIDTH_A = 2 ;
    DP16KD pdp_ram_0_1_6 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(scuba_vlo), .DIA1(Data[3]), .DIA0(Data[2]), .ADA13(wcount_12), 
        .ADA12(wcount_11), .ADA11(wcount_10), .ADA10(wcount_9), .ADA9(wcount_8), 
        .ADA8(wcount_7), .ADA7(wcount_6), .ADA6(wcount_5), .ADA5(wcount_4), 
        .ADA4(wcount_3), .ADA3(wcount_2), .ADA2(wcount_1), .ADA1(wcount_0), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(rcount_12), .ADB12(rcount_11), 
        .ADB11(rcount_10), .ADB10(rcount_9), .ADB9(rcount_8), .ADB8(rcount_7), 
        .ADB7(rcount_6), .ADB6(rcount_5), .ADB5(rcount_4), .ADB4(rcount_3), 
        .ADB3(rcount_2), .ADB2(rcount_1), .ADB1(rcount_0), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(Q[3]), .DOB0(Q[2]))
             /* synthesis MEM_LPC_FILE="gpif_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_2_5.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_2_5.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_2_5.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_2_5.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_2_5.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_2_5.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_2_5.GSR = "ENABLED" ;
    defparam pdp_ram_0_2_5.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_2_5.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_2_5.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_2_5.DATA_WIDTH_B = 2 ;
    defparam pdp_ram_0_2_5.DATA_WIDTH_A = 2 ;
    DP16KD pdp_ram_0_2_5 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(scuba_vlo), .DIA1(Data[5]), .DIA0(Data[4]), .ADA13(wcount_12), 
        .ADA12(wcount_11), .ADA11(wcount_10), .ADA10(wcount_9), .ADA9(wcount_8), 
        .ADA8(wcount_7), .ADA7(wcount_6), .ADA6(wcount_5), .ADA5(wcount_4), 
        .ADA4(wcount_3), .ADA3(wcount_2), .ADA2(wcount_1), .ADA1(wcount_0), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(rcount_12), .ADB12(rcount_11), 
        .ADB11(rcount_10), .ADB10(rcount_9), .ADB9(rcount_8), .ADB8(rcount_7), 
        .ADB7(rcount_6), .ADB6(rcount_5), .ADB5(rcount_4), .ADB4(rcount_3), 
        .ADB3(rcount_2), .ADB2(rcount_1), .ADB1(rcount_0), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(Q[5]), .DOB0(Q[4]))
             /* synthesis MEM_LPC_FILE="gpif_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_3_4.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_3_4.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_3_4.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_3_4.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_3_4.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_3_4.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_3_4.GSR = "ENABLED" ;
    defparam pdp_ram_0_3_4.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_3_4.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_3_4.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_3_4.DATA_WIDTH_B = 2 ;
    defparam pdp_ram_0_3_4.DATA_WIDTH_A = 2 ;
    DP16KD pdp_ram_0_3_4 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(scuba_vlo), .DIA1(Data[7]), .DIA0(Data[6]), .ADA13(wcount_12), 
        .ADA12(wcount_11), .ADA11(wcount_10), .ADA10(wcount_9), .ADA9(wcount_8), 
        .ADA8(wcount_7), .ADA7(wcount_6), .ADA6(wcount_5), .ADA5(wcount_4), 
        .ADA4(wcount_3), .ADA3(wcount_2), .ADA2(wcount_1), .ADA1(wcount_0), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(rcount_12), .ADB12(rcount_11), 
        .ADB11(rcount_10), .ADB10(rcount_9), .ADB9(rcount_8), .ADB8(rcount_7), 
        .ADB7(rcount_6), .ADB6(rcount_5), .ADB5(rcount_4), .ADB4(rcount_3), 
        .ADB3(rcount_2), .ADB2(rcount_1), .ADB1(rcount_0), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(Q[7]), .DOB0(Q[6]))
             /* synthesis MEM_LPC_FILE="gpif_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_4_3.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_4_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_4_3.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_4_3.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_4_3.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_4_3.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_4_3.GSR = "ENABLED" ;
    defparam pdp_ram_0_4_3.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_4_3.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_4_3.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_4_3.DATA_WIDTH_B = 2 ;
    defparam pdp_ram_0_4_3.DATA_WIDTH_A = 2 ;
    DP16KD pdp_ram_0_4_3 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(scuba_vlo), .DIA1(Data[9]), .DIA0(Data[8]), .ADA13(wcount_12), 
        .ADA12(wcount_11), .ADA11(wcount_10), .ADA10(wcount_9), .ADA9(wcount_8), 
        .ADA8(wcount_7), .ADA7(wcount_6), .ADA6(wcount_5), .ADA5(wcount_4), 
        .ADA4(wcount_3), .ADA3(wcount_2), .ADA2(wcount_1), .ADA1(wcount_0), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(rcount_12), .ADB12(rcount_11), 
        .ADB11(rcount_10), .ADB10(rcount_9), .ADB9(rcount_8), .ADB8(rcount_7), 
        .ADB7(rcount_6), .ADB6(rcount_5), .ADB5(rcount_4), .ADB4(rcount_3), 
        .ADB3(rcount_2), .ADB2(rcount_1), .ADB1(rcount_0), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(Q[9]), .DOB0(Q[8]))
             /* synthesis MEM_LPC_FILE="gpif_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_5_2.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_5_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_5_2.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_5_2.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_5_2.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_5_2.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_5_2.GSR = "ENABLED" ;
    defparam pdp_ram_0_5_2.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_5_2.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_5_2.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_5_2.DATA_WIDTH_B = 2 ;
    defparam pdp_ram_0_5_2.DATA_WIDTH_A = 2 ;
    DP16KD pdp_ram_0_5_2 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(scuba_vlo), .DIA1(Data[11]), .DIA0(Data[10]), .ADA13(wcount_12), 
        .ADA12(wcount_11), .ADA11(wcount_10), .ADA10(wcount_9), .ADA9(wcount_8), 
        .ADA8(wcount_7), .ADA7(wcount_6), .ADA6(wcount_5), .ADA5(wcount_4), 
        .ADA4(wcount_3), .ADA3(wcount_2), .ADA2(wcount_1), .ADA1(wcount_0), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(rcount_12), .ADB12(rcount_11), 
        .ADB11(rcount_10), .ADB10(rcount_9), .ADB9(rcount_8), .ADB8(rcount_7), 
        .ADB7(rcount_6), .ADB6(rcount_5), .ADB5(rcount_4), .ADB4(rcount_3), 
        .ADB3(rcount_2), .ADB2(rcount_1), .ADB1(rcount_0), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(Q[11]), .DOB0(Q[10]))
             /* synthesis MEM_LPC_FILE="gpif_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_6_1.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_6_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_6_1.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_6_1.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_6_1.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_6_1.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_6_1.GSR = "ENABLED" ;
    defparam pdp_ram_0_6_1.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_6_1.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_6_1.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_6_1.DATA_WIDTH_B = 2 ;
    defparam pdp_ram_0_6_1.DATA_WIDTH_A = 2 ;
    DP16KD pdp_ram_0_6_1 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(scuba_vlo), .DIA1(Data[13]), .DIA0(Data[12]), .ADA13(wcount_12), 
        .ADA12(wcount_11), .ADA11(wcount_10), .ADA10(wcount_9), .ADA9(wcount_8), 
        .ADA8(wcount_7), .ADA7(wcount_6), .ADA6(wcount_5), .ADA5(wcount_4), 
        .ADA4(wcount_3), .ADA3(wcount_2), .ADA2(wcount_1), .ADA1(wcount_0), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(rcount_12), .ADB12(rcount_11), 
        .ADB11(rcount_10), .ADB10(rcount_9), .ADB9(rcount_8), .ADB8(rcount_7), 
        .ADB7(rcount_6), .ADB6(rcount_5), .ADB5(rcount_4), .ADB4(rcount_3), 
        .ADB3(rcount_2), .ADB2(rcount_1), .ADB1(rcount_0), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(Q[13]), .DOB0(Q[12]))
             /* synthesis MEM_LPC_FILE="gpif_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_7_0.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_7_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_7_0.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_7_0.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_7_0.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_7_0.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_7_0.GSR = "ENABLED" ;
    defparam pdp_ram_0_7_0.RESETMODE = "SYNC" ;
    defparam pdp_ram_0_7_0.REGMODE_B = "OUTREG" ;
    defparam pdp_ram_0_7_0.REGMODE_A = "OUTREG" ;
    defparam pdp_ram_0_7_0.DATA_WIDTH_B = 2 ;
    defparam pdp_ram_0_7_0.DATA_WIDTH_A = 2 ;
    DP16KD pdp_ram_0_7_0 (.DIA17(scuba_vlo), .DIA16(scuba_vlo), .DIA15(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA13(scuba_vlo), .DIA12(scuba_vlo), .DIA11(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA9(scuba_vlo), .DIA8(scuba_vlo), .DIA7(scuba_vlo), 
        .DIA6(scuba_vlo), .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), 
        .DIA2(scuba_vlo), .DIA1(Data[15]), .DIA0(Data[14]), .ADA13(wcount_12), 
        .ADA12(wcount_11), .ADA11(wcount_10), .ADA10(wcount_9), .ADA9(wcount_8), 
        .ADA8(wcount_7), .ADA7(wcount_6), .ADA6(wcount_5), .ADA5(wcount_4), 
        .ADA4(wcount_3), .ADA3(wcount_2), .ADA2(wcount_1), .ADA1(wcount_0), 
        .ADA0(scuba_vlo), .CEA(wren_i), .OCEA(wren_i), .CLKA(Clock), .WEA(scuba_vhi), 
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), 
        .DIB17(scuba_vlo), .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), 
        .DIB13(scuba_vlo), .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), 
        .DIB9(scuba_vlo), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB13(rcount_12), .ADB12(rcount_11), 
        .ADB11(rcount_10), .ADB10(rcount_9), .ADB9(rcount_8), .ADB8(rcount_7), 
        .ADB7(rcount_6), .ADB6(rcount_5), .ADB5(rcount_4), .ADB4(rcount_3), 
        .ADB3(rcount_2), .ADB2(rcount_1), .ADB1(rcount_0), .ADB0(scuba_vlo), 
        .CEB(rden_i), .OCEB(scuba_vhi), .CLKB(Clock), .WEB(scuba_vlo), .CSB2(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), .DOA17(), .DOA16(), 
        .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), .DOA10(), .DOA9(), 
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), 
        .DOA0(), .DOB17(), .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), 
        .DOB11(), .DOB10(), .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(Q[15]), .DOB0(Q[14]))
             /* synthesis MEM_LPC_FILE="gpif_fifo.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3DX FF_43 (.D(ifcount_0), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(ifcount_1), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(ifcount_2), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(ifcount_3), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(ifcount_4), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(ifcount_5), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(ifcount_6), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(ifcount_7), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(ifcount_8), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(ifcount_9), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(ifcount_10), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(ifcount_11), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(ifcount_12), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(ifcount_13), .SP(fcnt_en), .CK(Clock), .CD(Reset), 
        .Q(fcount_13))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_29 (.D(empty_d), .CK(Clock), .PD(Reset), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_28 (.D(full_d), .CK(Clock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(iwcount_0), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(iwcount_1), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(iwcount_2), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(iwcount_3), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(iwcount_4), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(iwcount_5), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(iwcount_6), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(iwcount_7), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(iwcount_8), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(iwcount_9), .SP(wren_i), .CK(Clock), .CD(Reset), .Q(wcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(iwcount_10), .SP(wren_i), .CK(Clock), .CD(Reset), 
        .Q(wcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(iwcount_11), .SP(wren_i), .CK(Clock), .CD(Reset), 
        .Q(wcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(iwcount_12), .SP(wren_i), .CK(Clock), .CD(Reset), 
        .Q(wcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(iwcount_13), .SP(wren_i), .CK(Clock), .CD(Reset), 
        .Q(wcount_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(ircount_0), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(ircount_1), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(ircount_2), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(ircount_3), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(ircount_4), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(ircount_5), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(ircount_6), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(ircount_7), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(ircount_8), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(ircount_9), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(ircount_10), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(ircount_11), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(ircount_12), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(ircount_13), .SP(rden_i), .CK(Clock), .CD(Reset), .Q(rcount_13))
             /* synthesis GSR="ENABLED" */;

    defparam bdcnt_bctr_cia.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_cia.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_cia.INIT1 =  16'h66AA ;
    defparam bdcnt_bctr_cia.INIT0 =  16'h66AA ;
    CCU2C bdcnt_bctr_cia (.A0(scuba_vlo), .A1(cnt_con), .B0(scuba_vlo), 
        .B1(cnt_con), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(bdcnt_bctr_ci));

    defparam bdcnt_bctr_0.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_0.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_0.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_0.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_0 (.A0(fcount_0), .A1(fcount_1), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(bdcnt_bctr_ci), .S0(ifcount_0), .S1(ifcount_1), .COUT(co0));

    defparam bdcnt_bctr_1.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_1.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_1.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_1.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_1 (.A0(fcount_2), .A1(fcount_3), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(ifcount_2), .S1(ifcount_3), .COUT(co1));

    defparam bdcnt_bctr_2.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_2.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_2.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_2.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_2 (.A0(fcount_4), .A1(fcount_5), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1), .S0(ifcount_4), .S1(ifcount_5), .COUT(co2));

    defparam bdcnt_bctr_3.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_3.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_3.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_3.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_3 (.A0(fcount_6), .A1(fcount_7), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2), .S0(ifcount_6), .S1(ifcount_7), .COUT(co3));

    defparam bdcnt_bctr_4.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_4.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_4.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_4.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_4 (.A0(fcount_8), .A1(fcount_9), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3), .S0(ifcount_8), .S1(ifcount_9), .COUT(co4));

    defparam bdcnt_bctr_5.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_5.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_5.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_5.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_5 (.A0(fcount_10), .A1(fcount_11), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4), .S0(ifcount_10), .S1(ifcount_11), .COUT(co5));

    defparam bdcnt_bctr_6.INJECT1_1 = "NO" ;
    defparam bdcnt_bctr_6.INJECT1_0 = "NO" ;
    defparam bdcnt_bctr_6.INIT1 =  16'h99AA ;
    defparam bdcnt_bctr_6.INIT0 =  16'h99AA ;
    CCU2C bdcnt_bctr_6 (.A0(fcount_12), .A1(fcount_13), .B0(cnt_con), .B1(cnt_con), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5), .S0(ifcount_12), .S1(ifcount_13), .COUT(co6));

    defparam e_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam e_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam e_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam e_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C e_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam e_cmp_0.INJECT1_1 = "NO" ;
    defparam e_cmp_0.INJECT1_0 = "NO" ;
    defparam e_cmp_0.INIT1 =  16'h99AA ;
    defparam e_cmp_0.INIT0 =  16'h99AA ;
    CCU2C e_cmp_0 (.A0(rden_i), .A1(scuba_vlo), .B0(fcount_0), .B1(fcount_1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_1));

    defparam e_cmp_1.INJECT1_1 = "NO" ;
    defparam e_cmp_1.INJECT1_0 = "NO" ;
    defparam e_cmp_1.INIT1 =  16'h99AA ;
    defparam e_cmp_1.INIT0 =  16'h99AA ;
    CCU2C e_cmp_1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_2), .B1(fcount_3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(), .S1(), .COUT(co1_1));

    defparam e_cmp_2.INJECT1_1 = "NO" ;
    defparam e_cmp_2.INJECT1_0 = "NO" ;
    defparam e_cmp_2.INIT1 =  16'h99AA ;
    defparam e_cmp_2.INIT0 =  16'h99AA ;
    CCU2C e_cmp_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_4), .B1(fcount_5), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_1), .S0(), .S1(), .COUT(co2_1));

    defparam e_cmp_3.INJECT1_1 = "NO" ;
    defparam e_cmp_3.INJECT1_0 = "NO" ;
    defparam e_cmp_3.INIT1 =  16'h99AA ;
    defparam e_cmp_3.INIT0 =  16'h99AA ;
    CCU2C e_cmp_3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_6), .B1(fcount_7), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_1), .S0(), .S1(), .COUT(co3_1));

    defparam e_cmp_4.INJECT1_1 = "NO" ;
    defparam e_cmp_4.INJECT1_0 = "NO" ;
    defparam e_cmp_4.INIT1 =  16'h99AA ;
    defparam e_cmp_4.INIT0 =  16'h99AA ;
    CCU2C e_cmp_4 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_8), .B1(fcount_9), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_1), .S0(), .S1(), .COUT(co4_1));

    defparam e_cmp_5.INJECT1_1 = "NO" ;
    defparam e_cmp_5.INJECT1_0 = "NO" ;
    defparam e_cmp_5.INIT1 =  16'h99AA ;
    defparam e_cmp_5.INIT0 =  16'h99AA ;
    CCU2C e_cmp_5 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_10), .B1(fcount_11), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_1), .S0(), .S1(), .COUT(co5_1));

    defparam e_cmp_6.INJECT1_1 = "NO" ;
    defparam e_cmp_6.INJECT1_0 = "NO" ;
    defparam e_cmp_6.INIT1 =  16'h99AA ;
    defparam e_cmp_6.INIT0 =  16'h99AA ;
    CCU2C e_cmp_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(fcount_12), .B1(fcount_13), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5_1), .S0(), .S1(), .COUT(cmp_le_1_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_le_1_c), .S0(cmp_le_1), .S1(), .COUT());

    defparam g_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam g_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam g_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam g_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C g_cmp_ci_a (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam g_cmp_0.INJECT1_1 = "NO" ;
    defparam g_cmp_0.INJECT1_0 = "NO" ;
    defparam g_cmp_0.INIT1 =  16'h99AA ;
    defparam g_cmp_0.INIT0 =  16'h99AA ;
    CCU2C g_cmp_0 (.A0(fcount_0), .A1(fcount_1), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_2));

    defparam g_cmp_1.INJECT1_1 = "NO" ;
    defparam g_cmp_1.INJECT1_0 = "NO" ;
    defparam g_cmp_1.INIT1 =  16'h99AA ;
    defparam g_cmp_1.INIT0 =  16'h99AA ;
    CCU2C g_cmp_1 (.A0(fcount_2), .A1(fcount_3), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(), .S1(), .COUT(co1_2));

    defparam g_cmp_2.INJECT1_1 = "NO" ;
    defparam g_cmp_2.INJECT1_0 = "NO" ;
    defparam g_cmp_2.INIT1 =  16'h99AA ;
    defparam g_cmp_2.INIT0 =  16'h99AA ;
    CCU2C g_cmp_2 (.A0(fcount_4), .A1(fcount_5), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_2), .S0(), .S1(), .COUT(co2_2));

    defparam g_cmp_3.INJECT1_1 = "NO" ;
    defparam g_cmp_3.INJECT1_0 = "NO" ;
    defparam g_cmp_3.INIT1 =  16'h99AA ;
    defparam g_cmp_3.INIT0 =  16'h99AA ;
    CCU2C g_cmp_3 (.A0(fcount_6), .A1(fcount_7), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_2), .S0(), .S1(), .COUT(co3_2));

    defparam g_cmp_4.INJECT1_1 = "NO" ;
    defparam g_cmp_4.INJECT1_0 = "NO" ;
    defparam g_cmp_4.INIT1 =  16'h99AA ;
    defparam g_cmp_4.INIT0 =  16'h99AA ;
    CCU2C g_cmp_4 (.A0(fcount_8), .A1(fcount_9), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_2), .S0(), .S1(), .COUT(co4_2));

    defparam g_cmp_5.INJECT1_1 = "NO" ;
    defparam g_cmp_5.INJECT1_0 = "NO" ;
    defparam g_cmp_5.INIT1 =  16'h99AA ;
    defparam g_cmp_5.INIT0 =  16'h99AA ;
    CCU2C g_cmp_5 (.A0(fcount_10), .A1(fcount_11), .B0(wren_i), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_2), .S0(), .S1(), .COUT(co5_2));

    defparam g_cmp_6.INJECT1_1 = "NO" ;
    defparam g_cmp_6.INJECT1_0 = "NO" ;
    defparam g_cmp_6.INIT1 =  16'h99AA ;
    defparam g_cmp_6.INIT0 =  16'h99AA ;
    CCU2C g_cmp_6 (.A0(fcount_12), .A1(fcount_13), .B0(wren_i), .B1(wren_i_inv), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5_2), .S0(), .S1(), .COUT(cmp_ge_d1_c));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ge_d1_c), .S0(cmp_ge_d1), .S1(), .COUT());

    defparam w_ctr_cia.INJECT1_1 = "NO" ;
    defparam w_ctr_cia.INJECT1_0 = "NO" ;
    defparam w_ctr_cia.INIT1 =  16'h66AA ;
    defparam w_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_ctr_ci));

    defparam w_ctr_0.INJECT1_1 = "NO" ;
    defparam w_ctr_0.INJECT1_0 = "NO" ;
    defparam w_ctr_0.INIT1 =  16'h66AA ;
    defparam w_ctr_0.INIT0 =  16'h66AA ;
    CCU2C w_ctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_ctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0_3));

    defparam w_ctr_1.INJECT1_1 = "NO" ;
    defparam w_ctr_1.INJECT1_0 = "NO" ;
    defparam w_ctr_1.INIT1 =  16'h66AA ;
    defparam w_ctr_1.INIT0 =  16'h66AA ;
    CCU2C w_ctr_1 (.A0(wcount_2), .A1(wcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_3), .S0(iwcount_2), .S1(iwcount_3), .COUT(co1_3));

    defparam w_ctr_2.INJECT1_1 = "NO" ;
    defparam w_ctr_2.INJECT1_0 = "NO" ;
    defparam w_ctr_2.INIT1 =  16'h66AA ;
    defparam w_ctr_2.INIT0 =  16'h66AA ;
    CCU2C w_ctr_2 (.A0(wcount_4), .A1(wcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_3), .S0(iwcount_4), .S1(iwcount_5), .COUT(co2_3));

    defparam w_ctr_3.INJECT1_1 = "NO" ;
    defparam w_ctr_3.INJECT1_0 = "NO" ;
    defparam w_ctr_3.INIT1 =  16'h66AA ;
    defparam w_ctr_3.INIT0 =  16'h66AA ;
    CCU2C w_ctr_3 (.A0(wcount_6), .A1(wcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_3), .S0(iwcount_6), .S1(iwcount_7), .COUT(co3_3));

    defparam w_ctr_4.INJECT1_1 = "NO" ;
    defparam w_ctr_4.INJECT1_0 = "NO" ;
    defparam w_ctr_4.INIT1 =  16'h66AA ;
    defparam w_ctr_4.INIT0 =  16'h66AA ;
    CCU2C w_ctr_4 (.A0(wcount_8), .A1(wcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_3), .S0(iwcount_8), .S1(iwcount_9), .COUT(co4_3));

    defparam w_ctr_5.INJECT1_1 = "NO" ;
    defparam w_ctr_5.INJECT1_0 = "NO" ;
    defparam w_ctr_5.INIT1 =  16'h66AA ;
    defparam w_ctr_5.INIT0 =  16'h66AA ;
    CCU2C w_ctr_5 (.A0(wcount_10), .A1(wcount_11), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_3), .S0(iwcount_10), .S1(iwcount_11), .COUT(co5_3));

    defparam w_ctr_6.INJECT1_1 = "NO" ;
    defparam w_ctr_6.INJECT1_0 = "NO" ;
    defparam w_ctr_6.INIT1 =  16'h66AA ;
    defparam w_ctr_6.INIT0 =  16'h66AA ;
    CCU2C w_ctr_6 (.A0(wcount_12), .A1(wcount_13), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5_3), .S0(iwcount_12), .S1(iwcount_13), .COUT(co6_1));

    defparam r_ctr_cia.INJECT1_1 = "NO" ;
    defparam r_ctr_cia.INJECT1_0 = "NO" ;
    defparam r_ctr_cia.INIT1 =  16'h66AA ;
    defparam r_ctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_ctr_ci));

    defparam r_ctr_0.INJECT1_1 = "NO" ;
    defparam r_ctr_0.INJECT1_0 = "NO" ;
    defparam r_ctr_0.INIT1 =  16'h66AA ;
    defparam r_ctr_0.INIT0 =  16'h66AA ;
    CCU2C r_ctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_ctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_4));

    defparam r_ctr_1.INJECT1_1 = "NO" ;
    defparam r_ctr_1.INJECT1_0 = "NO" ;
    defparam r_ctr_1.INIT1 =  16'h66AA ;
    defparam r_ctr_1.INIT0 =  16'h66AA ;
    CCU2C r_ctr_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_4), .S0(ircount_2), .S1(ircount_3), .COUT(co1_4));

    defparam r_ctr_2.INJECT1_1 = "NO" ;
    defparam r_ctr_2.INJECT1_0 = "NO" ;
    defparam r_ctr_2.INIT1 =  16'h66AA ;
    defparam r_ctr_2.INIT0 =  16'h66AA ;
    CCU2C r_ctr_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_4), .S0(ircount_4), .S1(ircount_5), .COUT(co2_4));

    defparam r_ctr_3.INJECT1_1 = "NO" ;
    defparam r_ctr_3.INJECT1_0 = "NO" ;
    defparam r_ctr_3.INIT1 =  16'h66AA ;
    defparam r_ctr_3.INIT0 =  16'h66AA ;
    CCU2C r_ctr_3 (.A0(rcount_6), .A1(rcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_4), .S0(ircount_6), .S1(ircount_7), .COUT(co3_4));

    defparam r_ctr_4.INJECT1_1 = "NO" ;
    defparam r_ctr_4.INJECT1_0 = "NO" ;
    defparam r_ctr_4.INIT1 =  16'h66AA ;
    defparam r_ctr_4.INIT0 =  16'h66AA ;
    CCU2C r_ctr_4 (.A0(rcount_8), .A1(rcount_9), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3_4), .S0(ircount_8), .S1(ircount_9), .COUT(co4_4));

    defparam r_ctr_5.INJECT1_1 = "NO" ;
    defparam r_ctr_5.INJECT1_0 = "NO" ;
    defparam r_ctr_5.INIT1 =  16'h66AA ;
    defparam r_ctr_5.INIT0 =  16'h66AA ;
    CCU2C r_ctr_5 (.A0(rcount_10), .A1(rcount_11), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4_4), .S0(ircount_10), .S1(ircount_11), .COUT(co5_4));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam r_ctr_6.INJECT1_1 = "NO" ;
    defparam r_ctr_6.INJECT1_0 = "NO" ;
    defparam r_ctr_6.INIT1 =  16'h66AA ;
    defparam r_ctr_6.INIT0 =  16'h66AA ;
    CCU2C r_ctr_6 (.A0(rcount_12), .A1(rcount_13), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5_4), .S0(ircount_12), .S1(ircount_13), .COUT(co6_2));

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_7 MEM_LPC_FILE gpif_fifo.lpc
    // exemplar attribute pdp_ram_0_0_7 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_1_6 MEM_LPC_FILE gpif_fifo.lpc
    // exemplar attribute pdp_ram_0_1_6 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_2_5 MEM_LPC_FILE gpif_fifo.lpc
    // exemplar attribute pdp_ram_0_2_5 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_3_4 MEM_LPC_FILE gpif_fifo.lpc
    // exemplar attribute pdp_ram_0_3_4 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_4_3 MEM_LPC_FILE gpif_fifo.lpc
    // exemplar attribute pdp_ram_0_4_3 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_5_2 MEM_LPC_FILE gpif_fifo.lpc
    // exemplar attribute pdp_ram_0_5_2 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_6_1 MEM_LPC_FILE gpif_fifo.lpc
    // exemplar attribute pdp_ram_0_6_1 MEM_INIT_FILE 
    // exemplar attribute pdp_ram_0_7_0 MEM_LPC_FILE gpif_fifo.lpc
    // exemplar attribute pdp_ram_0_7_0 MEM_INIT_FILE 
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
