/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.7 */
/* Mon Nov 09 21:50:11 2020 */

/* parameterized module instance */
pll_ip __ (.CLKI( ), .CLKOP( ));
